<?php
// Automatically Generated by TestLink Installer - Mon, 12 Oct 15 17:46:46 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'testpc');
define('DB_PASS', 'testpc');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink-code');
define('DB_TABLE_PREFIX', '');
